version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demouser
      PGDATA: /ver/lib/postgresql/data/pgdata

    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
#то что не должно стираться при удаления контейнера
volumes:
  db-data: